const paragraphs = [
    "In the heart of the bustling city stood an old library that many had forgotten. Its doors creaked with age, and its walls whispered stories from centuries past. Dust danced in the sunlight that streamed through stained glass windows. Children once gathered here, listening to tales of dragons, knights, and distant lands. Now, silence reigned, broken only by the occasional turning of a page. But for those who still wandered in, the magic remained. Every book held a portal to another world, waiting for curious minds to unlock its secrets and explore the infinite worlds beyond the paper." ,
    "Technology has dramatically changed the way we live, work, and interact with the world around us. In just a few decades, we've gone from handwritten letters to instant global messaging, and from dial-up internet to high-speed wireless connections. People can now work remotely, learn new skills online, and even consult doctors from their homes. However, this digital evolution comes with its own set of challenges, such as screen addiction, online privacy, and the growing need for digital literacy. Balancing the benefits and downsides of technology is key to thriving in this fast-changing world.",
    "The mountain trail was steep, winding through thick pine forests and rocky slopes. Every step forward was a battle against gravity and exhaustion. But the reward was worth the effort. As the hiker reached the summit, the landscape unfolded in breathtaking beauty - rolling hills, distant lakes, and a sky painted in shades of orange and pink. A cool breeze brushed across their face, carrying the scent of wildflowers and fresh earth. At that moment, every hardship felt distant, replaced by a sense of peace and perspective that only nature can provide." ,
    "Learning a new language is not just about memorizing vocabulary or mastering grammar rules. It's a journey into a different culture, a new way of thinking, and a broader understanding of how people express themselves. The process can be frustrating at times, especially when progress feels slow or mistakes are frequent. But persistence is key. With consistent effort and real-world practice, fluency becomes more attainable. Conversations become smoother, listening becomes sharper, and confidence begins to grow. Over time, language learners gain more than just a skill - they gain access to an entirely new way of connecting with others." ,
    "Rain began to fall gently, tapping against the window like a soft drumbeat. Inside the cozy café, people sipped their drinks, lost in thought or quiet conversation. The aroma of fresh coffee mixed with the sound of jazz playing softly in the background. A writer sat in the corner, fingers tapping the keyboard, weaving a story inspired by the very atmosphere around them. Outside, umbrellas bloomed like flowers on the wet sidewalk. Moments like these, though simple, carry a kind of beauty that often goes unnoticed - a reminder to slow down and savor the present.",
    "The morning sunlight streamed through the curtains, warming the wooden floorboards and casting golden patterns on the walls. Outside, birds sang cheerfully as the world began to wake up. The smell of toast and coffee drifted from the kitchen, mingling with the soft hum of a radio playing in the background. It was the kind of peaceful start to the day that made everything feel calm and manageable. In a world that often moves too fast, these slow, quiet moments remind us that life doesn't always need to be rushed to be meaningful.",
    "Creativity isn't limited to artists or musicians; it's something everyone possesses in different forms. Whether you're solving a complex problem, cooking a unique meal, or designing a new way to organize your day, creativity plays a role. The key is to give it space to grow. Allow yourself to make mistakes, explore new perspectives, and try ideas that might seem silly at first. Over time, creativity becomes a habit, not just a skill. It opens doors, sparks innovation, and helps people express themselves in ways that words alone cannot fully capture.",
    "During the stormy night, thunder rolled across the hills, shaking windows and waking restless sleepers. Lightning cracked through the sky like nature's own fireworks, illuminating the dark clouds in brief flashes. Trees swayed and creaked under the pressure of the wind, and rain pounded against rooftops in rhythmic waves. Yet inside the cabin, there was warmth — a fire in the hearth, soft blankets, and the comforting smell of woodsmoke. Storms may rage outside, but sometimes the most peaceful moments are found within the shelter they force us to seek." ,
    "The power of habit is often underestimated. Small actions repeated daily can lead to massive changes over time. Whether it's writing a page, reading a chapter, or taking a short walk, consistency turns effort into progress. The hardest part is usually starting — overcoming that initial resistance. But once a habit is formed, it becomes automatic, part of your identity. People don't always need motivation; they need systems that support their goals. The most successful people aren't always the most talented - they're often just the most consistent.",
    "Traveling to new places introduces more than just unfamiliar sights. It exposes you to different ways of life, new tastes, unexpected traditions, and moments that challenge your perspective. Standing in a crowded market in a foreign country, hearing a language you don't speak, and tasting food you've never tried can feel overwhelming — but also thrilling. The world is vast, and each corner holds a story, a flavor, a rhythm of life waiting to be experienced. Travel doesn't just show you the world - it shows you yourself from a new point of view.",
    "As the deadline approached, tension filled the room. Fingers raced across keyboards, coffee cups were refilled, and the sound of deep sighs echoed between bursts of productivity. But amidst the pressure, something magical happened — focus sharpened, ideas flowed, and teamwork strengthened. It's often in the final hours that people tap into their highest level of concentration. The brain kicks into gear, creativity surges, and distractions fade. While it's not always healthy to work this way, there's something undeniably powerful about the adrenaline that accompanies a ticking clock.",
    "The garden was alive with color. Red tulips swayed beside golden daffodils, and vines climbed wooden trellises, reaching for the sky. Bees buzzed from bloom to bloom, collecting nectar, unaware of how essential their role was. In one corner, a small fountain bubbled, attracting birds for a quick drink or a playful splash. Gardening requires patience — seeds take time to sprout, and flowers don't bloom overnight. But each season teaches its own lesson: how to grow, when to rest, and how beauty can emerge quietly, one day at a time.",
    "Failure is not the opposite of success - it's part of the journey. Every mistake teaches something that success often hides. It shows what doesn't work, where improvement is needed, and how to bounce back. The most accomplished people in the world have failed more times than most have even tried. What sets them apart isn't perfection but resilience. They learn, adapt, and try again. In a world that often praises instant results, remember that true mastery is built through trial, error, and persistence.",
    "The world of dreams is a strange place. One moment you're flying through the clouds, the next you're running through endless hallways. Some dreams leave you confused, others inspired. Scientists still don't fully understand why we dream, but many believe it's the brain's way of processing memories, emotions, and hidden thoughts. Dreams can be nonsensical or deeply meaningful, and some people even learn to control them through lucid dreaming. Whether you remember them or not, your dreams reflect the complex universe inside your mind.",
    "Learning to listen is one of the most underrated skills in communication. Often, people listen to reply rather than to understand. True listening requires presence - setting aside distractions and focusing entirely on what the other person is saying. It's in this space that trust grows, misunderstandings fade, and genuine connection forms. Whether in friendships, work, or family, being a good listener is more impactful than having the perfect response. Sometimes, what someone needs most is not advice, but simply to be heard and seen.",
    "The city buzzed with a constant hum of life - honking cars, chatter on the sidewalks, and the distant sound of construction echoing between buildings. People hurried past each other, eyes on phones or darting to catch the next train. Amid the chaos, a street performer played a haunting melody on a worn violin, momentarily captivating a few listeners. The melody wove its way through the noise, wrapping the cold air in warmth. For a brief second, time seemed to slow down, as if even the city took a breath.",
    "In the vast desert, where the horizon melts into the sky, a solitary traveler marched through the dunes. Each step was met with resistance from the shifting sands beneath his boots. The sun blazed overhead, unforgiving and relentless. Yet, he pressed on, guided by memory and a faint hope. Mirage-like thoughts of home flickered before his eyes—cool water, laughter, shade under trees. He whispered stories to the wind, hoping it would carry them far. The desert listened in silence, cradling his footsteps like secrets only the earth could keep.",
    "She walked through the old library with reverence, fingers tracing the spines of books older than her grandparents. Dust floated in golden beams of light sneaking through stained-glass windows. The silence wasn't empty - it was alive with stories waiting to be heard again. As she pulled a heavy volume from the shelf, a small note slipped out. It wasn't signed, just a sentence: “Meet me where stories begin.” Her heart raced. Was it recent? Ancient? Real? The mystery of it wrapped around her, and suddenly the books weren't the only thing calling her back.",
    "Late at night, when the world had settled and the only sounds were crickets and a distant train, he sat by the window and watched the stars. Thoughts crowded his mind - about the choices he made, the paths not taken, and the dreams that kept him awake. The moonlight washed over the floor, soft and silent. Somewhere deep down, he knew that the stillness of this moment held clarity he couldn't find in the rush of the day. The silence wasn't lonely - it was honest. And sometimes, that was enough.",
    "The forest after the rain was a world transformed. The leaves glistened with droplets, and the scent of earth and moss filled the air. Birds resumed their song cautiously, as if checking whether the storm had truly passed. A child ran barefoot on the muddy path, laughter echoing through the trees. With each splash and stumble, she discovered joy untouched by screens or noise. Her dog followed, tail wagging, occasionally chasing butterflies that dared to fly low. In that moment, nature wasn't just a backdrop - it was the whole world.",
]

export default paragraphs